import { InlineKeyboard } from "../keyboard/index.js";
import type { InlineKeyboardButton } from "../api/types.js";

export interface Page<T> { items: T[]; page: number; pageCount: number; hasPrevious: boolean; hasNext: boolean }
export function paginate<T>(items: readonly T[], page: number, pageSize: number): Page<T> { if (!Number.isInteger(page) || page < 0) throw new RangeError("page must be a non-negative integer"); if (!Number.isInteger(pageSize) || pageSize < 1) throw new RangeError("pageSize must be a positive integer"); const pageCount = Math.max(1, Math.ceil(items.length / pageSize)); const safePage = Math.min(page, pageCount - 1); const start = safePage * pageSize; return { items: items.slice(start, start + pageSize) as T[], page: safePage, pageCount, hasPrevious: safePage > 0, hasNext: safePage < pageCount - 1 }; }
export function paginationButtons(page: Page<unknown>, prefix: string): InlineKeyboardButton[] { const buttons: InlineKeyboardButton[] = []; if (page.hasPrevious) buttons.push({ text: "Previous", callback_data: `${prefix}:page:${page.page - 1}` }); buttons.push({ text: `${page.page + 1}/${page.pageCount}`, callback_data: `${prefix}:noop` }); if (page.hasNext) buttons.push({ text: "Next", callback_data: `${prefix}:page:${page.page + 1}` }); return buttons; }

export interface MenuItem { id: string; label: string; callbackData?: string; url?: string; visible?: boolean | (() => boolean | Promise<boolean>); permission?: string }
export class Menu { private readonly itemsList: MenuItem[] = []; private readonly parents: string[] = []; constructor(readonly id: string) {} item(item: MenuItem): this { this.itemsList.push(item); return this; } breadcrumb(label: string): this { this.parents.push(label); return this; } async build(): Promise<InlineKeyboard> { const keyboard = new InlineKeyboard(); for (const item of this.itemsList) { const visible = typeof item.visible === "function" ? await item.visible() : item.visible ?? true; if (!visible) continue; if (item.url) keyboard.url(item.label, item.url); else keyboard.text(item.label, item.callbackData ?? `${this.id}:${item.id}`); } return keyboard; } get breadcrumbs(): readonly string[] { return this.parents; } }
